DROP TABLE LOGS.logtable;
DROP TABLE DS.md_ledger_account_s;
DROP TABLE DS.md_exchange_rate_d;
DROP TABLE DS.md_currency_d;
DROP TABLE ds.md_account_d;
DROP TABLE ds.ft_posting_f;
DROP TABLE ds.ft_balance_f;
DROP SCHEMA logs;
DROP SCHEMA ds;